export const coseBilkentLayoutOptions = {
  name: "cose-bilkent" as const,
  animate: "end" as const,
  animationDuration: 600,
  nodeDimensionsIncludeLabels: true,
  idealEdgeLength: 150,
  nodeRepulsion: 6500,
  edgeElasticity: 0.45,
  nestingFactor: 0.1,
  gravity: 0.25,
  numIter: 2500,
  tile: true,
  tilingPaddingVertical: 20,
  tilingPaddingHorizontal: 20,
  fit: true,
  padding: 40,
};
